#coding=gbk
"""
Copyright (C), 2012-2015, Anything Connected Possibilities
Author: ACP2013
Version: 1.0
Date: 2013-05-11
Description: 微信公共账号云平台 接口命令码定义
Others:      
Key Class&Method List: 
History: 
1. Date: 2013-05-13
   Author: Allen
   Modification: create
"""
# 微信公共账号云平台命令码区段
WX_CLOUD_CMD_BASE      = 0x01000000

# 微信HTTP接口(PHP)与云平台(Python)接口命令码区段
WX_ITF_CMD_BASE      = WX_CLOUD_CMD_BASE + 0x10000

# 管理Portal接口(PHP)与云平台(Python)接口命令码区段
PORTAL_ITF_CMD_BASE  = WX_CLOUD_CMD_BASE + 0x20000

# 云平台内部命令码区段
CLOUD_INNER_CMD_BASE = WX_CLOUD_CMD_BASE + 0x30000

###############################################################################################
# 微信通过HTTP POST访问时，PHP转发消息内容
WX_ACCESS_HTTP_POST_FORWARD  = WX_ITF_CMD_BASE + 0x00


###############################################################################################
# 订阅管理
PORTAL_SUBSCRIBER_CMD_BASE = PORTAL_ITF_CMD_BASE + 0x1000
# 会员管理
PORTAL_MEMBER_CMD_BASE     = PORTAL_ITF_CMD_BASE + 0x2000
# 配送管理
PORTAL_DELIVERY_CMD_BASE   = PORTAL_ITF_CMD_BASE + 0x3000
# 内容管理
PORTAL_CONTENT_CMD_BASE    = PORTAL_ITF_CMD_BASE + 0x4000
# 事件管理
PORTAL_EVENT_CMD_BASE      = PORTAL_ITF_CMD_BASE + 0x5000

# 人工关联订阅者和会员
PORTAL_SUBSCRIBER_MEMBER_ASSOCIATE   = PORTAL_SUBSCRIBER_CMD_BASE + 0x000
# 订阅者信息查询
PORTAL_SUBSCRIBER_INFO_QUERY         = PORTAL_SUBSCRIBER_CMD_BASE + 0x001
# 订阅者分组管理
PORTAL_SUBSCRIBER_GROUP_CREATE       = PORTAL_SUBSCRIBER_CMD_BASE + 0x100
PORTAL_SUBSCRIBER_GROUP_REMOVE       = PORTAL_SUBSCRIBER_CMD_BASE + 0x101
PORTAL_SUBSCRIBER_GROUP_MODIFY       = PORTAL_SUBSCRIBER_CMD_BASE + 0x102
PORTAL_SUBSCRIBER_GROUP_QUERY        = PORTAL_SUBSCRIBER_CMD_BASE + 0x103
PORTAL_SUBSCRIBER_GROUP_ASSOCIATE    = PORTAL_SUBSCRIBER_CMD_BASE + 0x104

# 会员配置
PORTAL_MEMBER_MEMBER_CREATE = PORTAL_MEMBER_CMD_BASE + 0x000
PORTAL_MEMBER_MEMBER_REMOVE = PORTAL_MEMBER_CMD_BASE + 0x001
PORTAL_MEMBER_MEMBER_MODIFY = PORTAL_MEMBER_CMD_BASE + 0x002
PORTAL_MEMBER_MEMBER_QUERY  = PORTAL_MEMBER_CMD_BASE + 0x003

# 配送报表查询
PORTAL_DELIVERY_REPORT_QUERY = PORTAL_DELIVERY_CMD_BASE + 0x000

# 配送菜品配置
PORTAL_DELIVERY_VEGETABLE_CREATE = PORTAL_DELIVERY_CMD_BASE + 0x010
PORTAL_DELIVERY_VEGETABLE_REMOVE = PORTAL_DELIVERY_CMD_BASE + 0x011
PORTAL_DELIVERY_VEGETABLE_MODIFY = PORTAL_DELIVERY_CMD_BASE + 0x012
PORTAL_DELIVERY_VEGETABLE_QUERY  = PORTAL_DELIVERY_CMD_BASE + 0x013

# 配送菜单配置
PORTAL_DELIVERY_MEMBER_MENU_CFG = PORTAL_DELIVERY_CMD_BASE + 0x20

PORTAL_DELIVERY_MENU_CREATE = PORTAL_DELIVERY_CMD_BASE + 0x020
PORTAL_DELIVERY_MENU_REMOVE = PORTAL_DELIVERY_CMD_BASE + 0x021
PORTAL_DELIVERY_MENU_MODIFY = PORTAL_DELIVERY_CMD_BASE + 0x022
PORTAL_DELIVERY_MENU_QUERY  = PORTAL_DELIVERY_CMD_BASE + 0x023

# 欢迎词帮助信息设置
PORTAL_CONTENT_HELPTIPS_SET   = PORTAL_CONTENT_CMD_BASE + 0x000
PORTAL_CONTENT_HELPTIPS_QUERY = PORTAL_CONTENT_CMD_BASE + 0x001

# 主题栏目配置
PORTAL_CONTENT_SUBJECT_CREATE = PORTAL_CONTENT_CMD_BASE + 0x100
PORTAL_CONTENT_SUBJECT_REMOVE = PORTAL_CONTENT_CMD_BASE + 0x101
PORTAL_CONTENT_SUBJECT_MODIFY = PORTAL_CONTENT_CMD_BASE + 0x102
PORTAL_CONTENT_SUBJECT_QUERY  = PORTAL_CONTENT_CMD_BASE + 0x103
# 主题内容配置
PORTAL_CONTENT_ARTICLE_CREATE = PORTAL_CONTENT_CMD_BASE + 0x200
PORTAL_CONTENT_ARTICLE_REMOVE = PORTAL_CONTENT_CMD_BASE + 0x201
PORTAL_CONTENT_ARTICLE_MODIFY = PORTAL_CONTENT_CMD_BASE + 0x202
PORTAL_CONTENT_ARTICLE_QUERY  = PORTAL_CONTENT_CMD_BASE + 0x203
# 主题内容推送给订阅者
PORTAL_CONTENT_ARTICLE_SUBSCRIBER_PUSH = PORTAL_CONTENT_CMD_BASE + 0x300

# 事件查询
PORTAL_EVENT_EVENT_QUERY  = PORTAL_EVENT_CMD_BASE + 0x000
# 事件报告
PORTAL_EVENT_EVENT_REPORT = PORTAL_EVENT_CMD_BASE + 0x001
# 查询未读事件数
PORTAL_EVENT_UNREAD_QUERY = PORTAL_EVENT_CMD_BASE + 0x002
# 事件已读通知
PORTAL_EVENT_READ_NOTIFY  = PORTAL_EVENT_CMD_BASE + 0x003

# 订阅者消息事件直接回复
PORTAL_EVENT_MESSAGE_REPLY = PORTAL_EVENT_CMD_BASE + 0x004
# 订阅者消息事件分享
PORTAL_EVENT_MESSAGE_SHARE = PORTAL_EVENT_CMD_BASE + 0x005


###############################################################################################
CLOUD_SUBSCRIBER_MANAGER_CMD_BASE = CLOUD_INNER_CMD_BASE + 0x1000
CLOUD_PORTAL_MANAGER_CMD_BASE     = CLOUD_INNER_CMD_BASE + 0x2000

# 订阅者文本消息
CLOUD_WX_PUSH_TEXT_MSG           = CLOUD_SUBSCRIBER_MANAGER_CMD_BASE + 0x000
# 订阅者图片消息
CLOUD_WX_PUSH_IMAGE_MSG          = CLOUD_SUBSCRIBER_MANAGER_CMD_BASE + 0x001
# 订阅者地理位置消息
CLOUD_WX_PUSH_LOCATION_MSG       = CLOUD_SUBSCRIBER_MANAGER_CMD_BASE + 0x002
# 链接消息
CLOUD_WX_PUSH_LINK_MSG           = CLOUD_SUBSCRIBER_MANAGER_CMD_BASE + 0x003
# 事件消息
CLOUD_WX_PUSH_EVENT_MSG          = CLOUD_SUBSCRIBER_MANAGER_CMD_BASE + 0x004
# 订阅者状态机的事件消息
CLOUD_SUBSCRIBER_STATE_EVENT_MSG = CLOUD_SUBSCRIBER_MANAGER_CMD_BASE + 0x010
# 订阅者管理模块初始化消息
CLOUD_SUBSCRIBER_MANAGER_INIT_MSG = CLOUD_SUBSCRIBER_MANAGER_CMD_BASE + 0x011

# 主题内容的推送通知消息（Portal管理模块->订阅者管理模块）
CLOUD_PORTAL_ARTICLE_PUSH_MSG    = CLOUD_PORTAL_MANAGER_CMD_BASE + 0x000
# 文本消息的推送通知消息（Portal管理模块->订阅者管理模块）
CLOUD_PORTAL_TEXT_PUSH_MSG       = CLOUD_PORTAL_MANAGER_CMD_BASE + 0x001
# 内容更新通知消息（Portal管理模块->订阅者管理模块）
CLOUD_PORTAL_CONTENT_UPDATE_MSG  = CLOUD_PORTAL_MANAGER_CMD_BASE + 0x002
# 订阅者分组更新通知消息（Portal管理模块->订阅者管理模块）
CLOUD_PORTAL_SUB_GROUP_ASSOC_MSG = CLOUD_PORTAL_MANAGER_CMD_BASE + 0x003
# 主题内容上传到微信后台的通知消息（Portal管理模块->订阅者管理模块）
CLOUD_PORTAL_ARTICLE_UPLOAD_MSG  = CLOUD_PORTAL_MANAGER_CMD_BASE + 0x004
# 主题上传微信图文消息后将ID通知Portal更新（订阅者管理模块->Portal管理模块）
CLOUD_PORTAL_NEWS_ID_UPDATE_MSG  = CLOUD_PORTAL_MANAGER_CMD_BASE + 0x005


